group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Revolute2
    - Revolute4
    - Revolute6
    - Revolute9
    - Revolute41
    - Revolute43
  gains:
    Revolute2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute41:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Revolute43:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Revolute43
  gains:
    Revolute43:
      p: 100
      d: 1
      i: 1
      i_clamp: 1